### ISSUE TITLE
varnishlog shows... 172.17.42.1 for reqstart

### ISSUE THREAD

**Issue by hwongcom** [dell-cloud-marketplace/docker-varnish#1]
varnishlog shows... 172.17.42.1 for reqstart

how do i make it show the actual client ip instead of the docker container ip?

**Comment by davtrott** [comment]
Requests from localhost (eg: _curl -I http://localhost_) will result in varnishlog logging ReqStarts from the Docker Gateway IP: 172.17.42.1.  Requests from external client IPs should log correctly.
You could use the Docker Host's actual IP Address instead of _http://localhost_ and that should appear in the varnishlog ReqStart instead of the Docker Gateway IP.
